packages:
  - "services/*"
  - "libs/*"
allowBuilds:
  '@firebase/util': true
  mongodb-memory-server: true
  protobufjs: true
minimumReleaseAgeExclude:
  - '@turbo/darwin-64@2.10.12'
  - '@turbo/darwin-arm64@2.10.12'
  - '@turbo/linux-64@2.10.12'
  - '@turbo/linux-arm64@2.10.12'
  - '@turbo/windows-64@2.10.12'
  - '@turbo/windows-arm64@2.10.12'
  - mongoose@9.9.4
  - turbo@2.10.12
  - axios@1.20.0
